Support linux with unmounter

diff --git a/bin/bin/unmounter b/bin/bin/unmounter
--- a/bin/bin/unmounter
+++ b/bin/bin/unmounter
@@ -2,19 +2,42 @@
 
 set -e
 
-DEVICE=$(diskutil list | grep '/dev' | cut -d ' ' -f 1 | fzf --preview 'diskutil info {}')
+unmount_darwin() {
+    DEVICE=$(diskutil list | grep '/dev' | cut -d ' ' -f 1 | fzf --preview 'diskutil info {}')
 
+    # Sanity check the device
+    diskutil info $DEVICE | grep "Device Location" | grep -q External || {
+        echo "Chosen disk is an internal disk, so cannot unmount" >&2
+        exit 1
+    }
 
-# Sanity check the device
-diskutil info $DEVICE | grep "Device Location" | grep -q External || {
-    echo "Chosen disk is an internal disk, so cannot unmount" >&2
-    exit 1
+    diskutil info $DEVICE | grep "Virtual" | grep -q No || {
+        echo "Chosen disk is virtual, so cannot unmount" >&2
+        exit 1
+    }
+
+    echo "Unmounting $DEVICE"
+    diskutil unmountDisk $DEVICE
 }
 
-diskutil info $DEVICE | grep "Virtual" | grep -q No || {
-    echo "Chosen disk is virtual, so cannot unmount" >&2
-    exit 1
+unmount_linux() {
+    DEVICE=$(df | grep '/run/media' | cut -d ' ' -f 1 | fzf --preview 'df {}')
+
+    echo "Unmounting $DEVICE"
+    umount $DEVICE
 }
 
-echo "Unmounting $DEVICE"
-diskutil unmountDisk $DEVICE
+case $OSTYPE in
+    darwin*)
+        unmount_darwin
+        ;;
+    linux*)
+        unmount_linux
+        ;;
+    *)
+        echo "Unsupported os type" >&2
+        exit 1
+        ;;
+esac
+
+
