Set up view-note
This supports an argument and completion

diff --git a/bin/bin/view-note b/bin/bin/view-note
--- a/bin/bin/view-note
+++ b/bin/bin/view-note
@@ -2,22 +2,34 @@
 
 set -eou pipefail
 
-noteName=${HOME}/notes/html/note-$(date +%Y-%m-%d).html
-
+outName=""
 function buildnote() {
-    srcName="$(echo $noteName | sed 's/html/src/' | sed 's/html/md/')"
-    test -f $srcName || {
-        echo "Cannot find source file $sourceName" >&2
+    noteName=$1
+
+    test -f $noteName || {
+        echo "Cannot find source file $noteName" >&2
         return 1
     }
 
+    outName="$(echo $noteName | sed 's/src/html/' | sed 's/md/html/')"
     pandoc \
         -t html5 \
         --template Github.html5 \
         --metadata title="Notes" \
-        -o "$noteName" $srcName
-    wait
+        -o "$outName" $noteName
 }
 
-buildnote
-open $noteName
+main() {
+
+    local noteName
+    if [[ $# -eq 0 ]]; then
+        noteName=${HOME}/notes/src/note-$(date +%Y-%m-%d).md
+    else
+        noteName=$1
+    fi
+
+    buildnote $noteName
+    open $outName
+}
+
+main $*
